#!/usr/bin/env bash
# Foundation 001 §6.5 / §10 — run the provisioning procedure against the CI container and
# export the resulting configuration NAMES with per-run values for test:db.
#
# The values are generated by provision.sh for this run only, live in the job's environment,
# are masked in the job log, and are discarded with the runner. They are not GitHub secrets;
# CI holds no secret (§10). Each URL gains the verified-TLS options the application requires.
#
# Usage: scripts/ci/provision-and-export.sh --admin-url <url> --ca-file <path> [--env-file <path>] [--instance-id <uuid>]
#   Writes to $GITHUB_ENV when set, otherwise to --env-file (KEY='VALUE' lines, mode 600).
#   --instance-id re-runs against an already provisioned local database (rotating its role
#   passwords); without it a fresh id is generated, which a provisioned database refuses.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."
admin=""; ca=""; envfile=""; instance_id=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --admin-url) admin="$2"; shift 2 ;;
    --ca-file)   ca="$2"; shift 2 ;;
    --env-file)  envfile="$2"; shift 2 ;;
    --instance-id) instance_id="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[[ -n "$admin" && -n "$ca" ]] || { echo "--admin-url and --ca-file are required" >&2; exit 2; }
target="${GITHUB_ENV:-$envfile}"
[[ -n "$target" ]] || { echo "set GITHUB_ENV or pass --env-file" >&2; exit 2; }
# GITHUB_ENV takes raw KEY=VALUE lines; a shell env file needs the values quoted (URLs carry '&').
if [[ -n "${GITHUB_ENV:-}" ]]; then put() { echo "$1=$2" >> "$target"; }; else put() { printf "%s='%s'\n" "$1" "$2" >> "$target"; }; fi

[[ -n "$instance_id" ]] || instance_id="$(cat /proc/sys/kernel/random/uuid)"
out="$(mktemp)"; trap 'rm -f "$out"' EXIT
scripts/provision/provision.sh --target container --environment ci \
  --instance-id "$instance_id" --admin-url "$admin" > "$out"

ssl='?sslmode=verify-full&sslrootcert=system'
put PROVIDER_MESH_INSTANCE_ID "$instance_id"
put PROVIDER_MESH_ENVIRONMENT ci
put NODE_EXTRA_CA_CERTS "$ca"
put PM_CI_ADMIN_URL "$admin"
for name in PROVIDER_MESH_DATABASE_URL PROVIDER_MESH_AUDIT_URL PROVIDER_MESH_MIGRATE_URL \
            PROVIDER_MESH_AUDIT_MIGRATE_URL PROVIDER_MESH_AUDIT_READER_URL; do
  url="$(grep -E "^${name}=" "$out" | head -n1 | cut -d= -f2-)"
  [[ -n "$url" ]] || { echo "provisioning output lacks $name" >&2; exit 1; }
  password="$(printf '%s' "$url" | sed -nE 's#^postgresql://[^:]+:([^@]+)@.*#\1#p')"
  [[ -n "${GITHUB_ACTIONS:-}" && -n "$password" ]] && echo "::add-mask::$password"
  put "$name" "${url}${ssl}"
done
chmod 600 "$target" 2>/dev/null || true
echo "provisioned ci environment; 7 configuration names exported"
